// Stub for webhook trigger events (some EE-only)
export enum WebhookTriggerEvents {
  BOOKING_CREATED = "BOOKING_CREATED",
  BOOKING_RESCHEDULED = "BOOKING_RESCHEDULED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",
  BOOKING_REJECTED = "BOOKING_REJECTED",
  BOOKING_REQUESTED = "BOOKING_REQUESTED",
  BOOKING_PAYMENT_INITIATED = "BOOKING_PAYMENT_INITIATED",
  BOOKING_PAID = "BOOKING_PAID",
  MEETING_ENDED = "MEETING_ENDED",
  RECORDING_READY = "RECORDING_READY",
  INSTANT_MEETING = "INSTANT_MEETING",
  FORM_SUBMITTED = "FORM_SUBMITTED",
}
